const FontFaceObserver = require('fontfaceobserver')
export const dewi = new FontFaceObserver('RF Dewi Expanded Black Custom')
// export const dewiReg = new FontFaceObserver('RF Dewi Regular')
// export const dewiExp = new FontFaceObserver('RF Dewi Expanded Black')
// export const dewiExt = new FontFaceObserver('RF Dewi Extended Bold')
export const china = new FontFaceObserver('Typeface Custom')
